### PR TITLE
Protect against concurrent map writes in status command

### LINKED ISSUE #13: Concurrent map writes
Seems to be happening with greater frequency. 

The output suggests a race condition in `status.go`, but it has got a waitgroup. Not knowing anything about wait groups personally, perhaps it's not working as intended..?

```
func GetProjectStatus(prefix string, locales []string) ProjectStatus {
	var wg sync.WaitGroup
	statuses := ProjectStatus{}

	for _, projectFilepath := range ProjectConfig.Files() {
		remoteFilePath := findIdenticalRemoteFileOrPush(projectFilepath, prefix)

		for _, l := range locales {
			wg.Add(1)
			go func(remotefile, locale string) {
				defer wg.Done()
				statuses.Add(remotefile, locale, MustStatus(remotefile, locale))
			}(remoteFilePath, l)
		}
	}
	wg.Wait()

	return statuses
}
```

We might get some help from [this](https://blog.golang.org/race-detector
) race condition helper flag

```

fatal error: concurrent map writes
--
  |  
  | goroutine 162 [running]:
  | runtime.throw(0x7bb4bc, 0x15)
  | /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420487d58 sp=0xc420487d38
  | runtime.mapassign(0x7585a0, 0xc420019620, 0xc420487e78, 0x70)
  | /usr/local/go/src/runtime/hashmap.go:499 +0x667 fp=0xc420487df8 sp=0xc420487d58
  | main.GetProjectStatus.func1(0xc4201422d0, 0xc42019c630, 0xc42033d260, 0x70, 0xc42014229e, 0x2)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:65 +0x1ef fp=0xc420487fb0 sp=0xc420487df8
  | runtime.goexit()
  | /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420487fb8 sp=0xc420487fb0
  | created by main.GetProjectStatus
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:66 +0x1a5
  |  
  | goroutine 1 [select]:
  | net/http.(*persistConn).roundTrip(0xc420077320, 0xc4201ae360, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/http/transport.go:1898 +0x974
  | net/http.(*Transport).RoundTrip(0x963d60, 0xc4204be900, 0x963d60, 0xed1e60d82, 0x10662a42)
  | /usr/local/go/src/net/http/transport.go:391 +0x74c
  | net/http.send(0xc4204be800, 0x9362e0, 0x963d60, 0xed1e60d82, 0x10662a42, 0x968540, 0x0, 0x8, 0xc42011e170, 0x410c68)
  | /usr/local/go/src/net/http/client.go:249 +0x162
  | net/http.(*Client).send(0xc420019440, 0xc4204be800, 0xed1e60d82, 0x10662a42, 0x968540, 0xc42011e170, 0x0, 0x1, 0x409f0e)
  | /usr/local/go/src/net/http/client.go:173 +0x108
  | net/http.(*Client).Do(0xc420019440, 0xc4204be800, 0xc, 0x7c09b6, 0x21)
  | /usr/local/go/src/net/http/client.go:595 +0x254
  | net/http.(*Client).Post(0xc420019440, 0xc42019d5f0, 0x26, 0x7c09b6, 0x21, 0x9368e0, 0xc4201ae220, 0x0, 0xc4200f40d8, 0x2)
  | /usr/local/go/src/net/http/client.go:720 +0xf8
  | net/http.(*Client).PostForm(0xc420019440, 0xc42019d5f0, 0x26, 0xc42019d5c0, 0xa, 0xc42019d5f0, 0x26)
  | /usr/local/go/src/net/http/client.go:752 +0xdd
  | github.com/99designs/smartling.(*Client).doRequestAndUnmarshalData(0xc420010c80, 0x7b7085, 0xa, 0x79dec0, 0xc420502100, 0x72b800, 0xc4201ae080, 0x98, 0xe0d10460580d4b96)
  | /go/src/github.com/99designs/smartling/smartling.go:41 +0x2ae
  | github.com/99designs/smartling.(*Client).List(0xc420010c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/file.go:195 +0x110
  | github.com/99designs/smartling.(*FaultTolerantClient).List.func1(0x40, 0x6d)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:81 +0x73
  | github.com/99designs/smartling.(*FaultTolerantClient).execWithRetry(0xc420015a30, 0xc4200f43d0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:50 +0x3c
  | github.com/99designs/smartling.(*FaultTolerantClient).List(0xc420015a30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:83 +0x114
  | main.fetchRemoteFileList(0xc420119280, 0x73ce60, 0xc420119290)
  | /go/src/github.com/99designs/smartling/cli/smartling/project.go:45 +0x7e
  | main.getRemoteFileList(0xc420214840, 0x40, 0xc420019530)
  | /go/src/github.com/99designs/smartling/cli/smartling/project.go:60 +0x5f
  | main.findIdenticalRemoteFileOrPush(0xc420214840, 0x40, 0xc420019530, 0x24, 0xc4204fd200, 0x5b)
  | /go/src/github.com/99designs/smartling/cli/smartling/translate.go:98 +0x80
  | main.GetProjectStatus(0xc420019530, 0x24, 0xc4201a0000, 0x7, 0x8, 0x40cb42)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:59 +0xe7
  | main.glob..func12(0xc4200c0640)
  | /go/src/github.com/99designs/smartling/cli/smartling/project.go:110 +0xe4
  | github.com/99designs/smartling/vendor/github.com/codegangsta/cli.HandleAction(0x73b6e0, 0x7c9cb0, 0xc4200c0640, 0xc42005cd00, 0x0)
  | /go/src/github.com/99designs/smartling/vendor/github.com/codegangsta/cli/app.go:487 +0x7c
  | github.com/99designs/smartling/vendor/github.com/codegangsta/cli.Command.Run(0x7b5df5, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7c4e39, 0x2d, 0x0, ...)
  | /go/src/github.com/99designs/smartling/vendor/github.com/codegangsta/cli/command.go:193 +0xb72
  | github.com/99designs/smartling/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc4200ce820, 0xc4200c03c0, 0x0, 0x0)
  | /go/src/github.com/99designs/smartling/vendor/github.com/codegangsta/cli/app.go:374 +0xacc
  | github.com/99designs/smartling/vendor/github.com/codegangsta/cli.Command.startApp(0x7b6287, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7bd88f, 0x1a, 0x0, ...)
  | /go/src/github.com/99designs/smartling/vendor/github.com/codegangsta/cli/command.go:280 +0x824
  | github.com/99designs/smartling/vendor/github.com/codegangsta/cli.Command.Run(0x7b6287, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7bd88f, 0x1a, 0x0, ...)
  | /go/src/github.com/99designs/smartling/vendor/github.com/codegangsta/cli/command.go:79 +0x14c7
  | github.com/99designs/smartling/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200ce4e0, 0xc420010200, 0x4, 0x4, 0x0, 0x0)
  | /go/src/github.com/99designs/smartling/vendor/github.com/codegangsta/cli/app.go:250 +0x7d0
  | main.main()
  | /go/src/github.com/99designs/smartling/cli/smartling/main.go:126 +0x7b7
  |  
  | goroutine 17 [syscall, locked to thread]:
  | runtime.goexit()
  | /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
  |  
  | goroutine 221 [chan receive]:
  | net/http.(*Transport).getConn.func2.1(0xc42005d4a0, 0x963d60, 0x7ca000)
  | /usr/local/go/src/net/http/transport.go:897 +0x60
  | created by net/http.(*Transport).getConn.func2
  | /usr/local/go/src/net/http/transport.go:901 +0x7a
  |  
  | goroutine 12 [IO wait]:
  | net.runtime_pollWait(0x7f8383d86000, 0x72, 0x3)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc420053418, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc420053418, 0xc4200a9800, 0x800)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc4200533b0, 0xc4200a9800, 0x800, 0x800, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc42011e008, 0xc4200a9800, 0x800, 0x800, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc42011a390, 0x7f8383d41050, 0xc42011e008, 0x5, 0xc42011e008, 0xc420039838)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc420128000, 0x7ca417, 0xc420128120, 0x452090)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*Conn).Read(0xc420128000, 0xc420133000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
  | net/http.(*persistConn).Read(0xc4200777a0, 0xc420133000, 0x1000, 0x1000, 0x5, 0x450520, 0xc420110660)
  | /usr/local/go/src/net/http/transport.go:1316 +0x14b
  | bufio.(*Reader).fill(0xc4201104e0)
  | /usr/local/go/src/bufio/bufio.go:97 +0x117
  | bufio.(*Reader).Peek(0xc4201104e0, 0x1, 0xc420039be5, 0xc420142d01, 0x4, 0xc42057bc80, 0x0)
  | /usr/local/go/src/bufio/bufio.go:129 +0x67
  | net/http.(*persistConn).readLoop(0xc4200777a0)
  | /usr/local/go/src/net/http/transport.go:1474 +0x196
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1117 +0xa35
  |  
  | goroutine 13 [select]:
  | net/http.(*persistConn).writeLoop(0xc4200777a0)
  | /usr/local/go/src/net/http/transport.go:1704 +0x43a
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1118 +0xa5a
  |  
  | goroutine 168 [runnable]:
  | syscall.Syscall(0x1, 0x5, 0xc4200fc800, 0x196, 0x196, 0x196, 0x0)
  | /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
  | syscall.write(0x5, 0xc4200fc800, 0x196, 0x400, 0x77, 0x0, 0x0)
  | /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1064 +0x55
  | syscall.Write(0x5, 0xc4200fc800, 0x196, 0x400, 0xc4200fc80d, 0x189, 0x3f3)
  | /usr/local/go/src/syscall/syscall_unix.go:181 +0x49
  | net.(*netFD).Write(0xc4205625b0, 0xc4200fc800, 0x196, 0x400, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/fd_unix.go:332 +0x15e
  | net.(*conn).Write(0xc42000e0a8, 0xc4200fc800, 0x196, 0x400, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:193 +0x70
  | crypto/tls.(*Conn).write(0xc4204fb500, 0xc4200fc800, 0x196, 0x400, 0xc42026f980, 0x7ca401, 0xc4204fb514)
  | /usr/local/go/src/crypto/tls/conn.go:832 +0x192
  | crypto/tls.(*Conn).writeRecordLocked(0xc4204fb500, 0x7ca417, 0xc420508000, 0x179, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:909 +0x34b
  | crypto/tls.(*Conn).Write(0xc4204fb500, 0xc420508000, 0x179, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1068 +0x202
  | net/http.persistConnWriter.Write(0xc42018f8c0, 0xc420508000, 0x179, 0x1000, 0x7b54e4, 0x4, 0x73ce60)
  | /usr/local/go/src/net/http/transport.go:1133 +0x52
  | bufio.(*Writer).Flush(0xc4201160c0, 0x935aa0, 0xc4201160c0)
  | /usr/local/go/src/bufio/bufio.go:566 +0x75
  | net/http.(*persistConn).writeLoop(0xc42018f8c0)
  | /usr/local/go/src/net/http/transport.go:1709 +0x3d7
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1118 +0xa5a
  |  
  | goroutine 143 [select]:
  | net/http.(*persistConn).roundTrip(0xc420438240, 0xc4201c1b20, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/http/transport.go:1898 +0x974
  | net/http.(*Transport).RoundTrip(0x963d60, 0xc4204d4800, 0x963d60, 0xed1e60d81, 0x3949c478)
  | /usr/local/go/src/net/http/transport.go:391 +0x74c
  | net/http.send(0xc4204d4700, 0x9362e0, 0x963d60, 0xed1e60d81, 0x3949c478, 0x968540, 0x0, 0x8, 0xc42000e098, 0x410c68)
  | /usr/local/go/src/net/http/client.go:249 +0x162
  | net/http.(*Client).send(0xc420019440, 0xc4204d4700, 0xed1e60d81, 0x3949c478, 0x968540, 0xc42000e098, 0x0, 0x1, 0x409f0e)
  | /usr/local/go/src/net/http/client.go:173 +0x108
  | net/http.(*Client).Do(0xc420019440, 0xc4204d4700, 0xc, 0x7c09b6, 0x21)
  | /usr/local/go/src/net/http/client.go:595 +0x254
  | net/http.(*Client).Post(0xc420019440, 0xc4201c6c00, 0x28, 0x7c09b6, 0x21, 0x9368e0, 0xc4201c19c0, 0x0, 0xc420035988, 0x2)
  | /usr/local/go/src/net/http/client.go:720 +0xf8
  | net/http.(*Client).PostForm(0xc420019440, 0xc4201c6c00, 0x28, 0xc4201c6bd0, 0xc, 0xc4201c6c00, 0x28)
  | /usr/local/go/src/net/http/client.go:752 +0xdd
  | github.com/99designs/smartling.(*Client).doRequestAndUnmarshalData(0xc420010c80, 0x7b7c15, 0xc, 0x76dde0, 0xc4201c1920, 0x762820, 0xc420111140, 0x963d60, 0x93aa20)
  | /go/src/github.com/99designs/smartling/smartling.go:41 +0x2ae
  | github.com/99designs/smartling.(*Client).Status(0xc420010c80, 0xc42033d260, 0x70, 0xc420142267, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/file.go:208 +0x16f
  | github.com/99designs/smartling.(*FaultTolerantClient).Status.func1(0xab8, 0x2)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:89 +0x7e
  | github.com/99designs/smartling.(*FaultTolerantClient).execWithRetry(0xc420015a30, 0xc420447cb0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:50 +0x3c
  | github.com/99designs/smartling.(*FaultTolerantClient).Status(0xc420015a30, 0xc42033d260, 0x70, 0xc420142267, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:91 +0xf9
  | main.MustStatus(0xc42033d260, 0x70, 0xc420142267, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:13 +0xa1
  | main.GetProjectStatus.func1(0xc4201422d0, 0xc42019c630, 0xc42033d260, 0x70, 0xc420142267, 0x5)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:65 +0x97
  | created by main.GetProjectStatus
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:66 +0x1a5
  |  
  | goroutine 229 [select]:
  | net/http.setRequestCancel.func3(0x0, 0xc4201f90e0, 0xc4202f84c0, 0xc4201428f0, 0xc420254540)
  | /usr/local/go/src/net/http/client.go:320 +0x17c
  | created by net/http.setRequestCancel
  | /usr/local/go/src/net/http/client.go:330 +0x287
  |  
  | goroutine 157 [select]:
  | net/http.setRequestCancel.func3(0x0, 0xc42019c9c0, 0xc420116cc0, 0xc4201a67bc, 0xc42005dec0)
  | /usr/local/go/src/net/http/client.go:320 +0x17c
  | created by net/http.setRequestCancel
  | /usr/local/go/src/net/http/client.go:330 +0x287
  |  
  | goroutine 171 [select]:
  | net/http.setRequestCancel.func3(0x0, 0xc4200199e0, 0xc420116a00, 0xc4200152f8, 0xc42057b200)
  | /usr/local/go/src/net/http/client.go:320 +0x17c
  | created by net/http.setRequestCancel
  | /usr/local/go/src/net/http/client.go:330 +0x287
  |  
  | goroutine 195 [IO wait]:
  | net.runtime_pollWait(0x7f8383d85dc0, 0x72, 0x8)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc4205626f8, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc4205626f8, 0xc4204eac00, 0x400)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc420562690, 0xc4204eac00, 0x400, 0x400, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc42011e0b0, 0xc4204eac00, 0x400, 0x400, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc42019d9e0, 0x7f8383d41050, 0xc42011e0b0, 0x5, 0xc42011e0b0, 0xc420415878)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc420596380, 0x7ca417, 0xc4205964a0, 0xc420415a88)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*Conn).Read(0xc420596380, 0xc42047f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
  | net/http.(*persistConn).Read(0xc420077320, 0xc42047f000, 0x1000, 0x1000, 0xc420415b60, 0xa, 0xc420415b80)
  | /usr/local/go/src/net/http/transport.go:1316 +0x14b
  | bufio.(*Reader).fill(0xc4204a50e0)
  | /usr/local/go/src/bufio/bufio.go:97 +0x117
  | bufio.(*Reader).Peek(0xc4204a50e0, 0x1, 0xc4204a5140, 0xc4204b6480, 0x0, 0x0, 0x0)
  | /usr/local/go/src/bufio/bufio.go:129 +0x67
  | net/http.(*persistConn).readLoop(0xc420077320)
  | /usr/local/go/src/net/http/transport.go:1474 +0x196
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1117 +0xa35
  |  
  | goroutine 177 [IO wait]:
  | net.runtime_pollWait(0x7f8383d85a00, 0x72, 0x6)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc420052a08, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc420052a08, 0xc4204c7000, 0x1000)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc4200529a0, 0xc4204c7000, 0x1000, 0x1000, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc42000e108, 0xc4204c7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc42011a9c0, 0x7f8383d41050, 0xc42000e108, 0x5, 0xc42000e108, 0x3f3)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc4205a4380, 0xc420215314, 0xc420547b00, 0xc420547b78)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*clientHandshakeState).readFinished(0xc420547e50, 0xc4205a4475, 0xc, 0xc, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/handshake_client.go:584 +0x53
  | crypto/tls.(*Conn).clientHandshake(0xc4205a4380, 0x7ca4f0, 0xc4205a44a0)
  | /usr/local/go/src/crypto/tls/handshake_client.go:244 +0x109f
  | crypto/tls.(*Conn).Handshake(0xc4205a4380, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1307 +0x1a3
  | net/http.(*Transport).dialConn.func3(0x0, 0xc4205a4380, 0xc420117000, 0xc42039c540)
  | /usr/local/go/src/net/http/transport.go:1082 +0x42
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1087 +0xfec
  |  
  | goroutine 212 [select]:
  | net/http.setRequestCancel.func3(0x0, 0xc42019d8c0, 0xc420214880, 0xc42011950c, 0xc420110540)
  | /usr/local/go/src/net/http/client.go:320 +0x17c
  | created by net/http.setRequestCancel
  | /usr/local/go/src/net/http/client.go:330 +0x287
  |  
  | goroutine 173 [chan receive]:
  | net/http.(*Transport).dialConn(0x963d60, 0x93aa20, 0xc420014240, 0x0, 0xc420019ad0, 0x5, 0xc420140e80, 0x15, 0x73ce60, 0x0, ...)
  | /usr/local/go/src/net/http/transport.go:1088 +0x102e
  | net/http.(*Transport).getConn.func4(0x963d60, 0x93aa20, 0xc420014240, 0xc420019ce0, 0xc42057b500)
  | /usr/local/go/src/net/http/transport.go:908 +0x78
  | created by net/http.(*Transport).getConn
  | /usr/local/go/src/net/http/transport.go:910 +0x3a3
  |  
  | goroutine 90 [select]:
  | net/http.(*persistConn).writeLoop(0xc420438120)
  | /usr/local/go/src/net/http/transport.go:1704 +0x43a
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1118 +0xa5a
  |  
  | goroutine 193 [select]:
  | net/http.setRequestCancel.func3(0x0, 0xc4201f8750, 0xc4202f8300, 0xc420142328, 0xc42005c960)
  | /usr/local/go/src/net/http/client.go:320 +0x17c
  | created by net/http.setRequestCancel
  | /usr/local/go/src/net/http/client.go:330 +0x287
  |  
  | goroutine 233 [IO wait]:
  | net.runtime_pollWait(0x7f8383d85640, 0x72, 0x11)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc42011c3e8, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc42011c3e8, 0xc420029800, 0x400)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc42011c380, 0xc420029800, 0x400, 0x400, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc4201840c0, 0xc420029800, 0x400, 0x400, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc42024c3c0, 0x7f8383d41050, 0xc4201840c0, 0x5, 0xc4201840c0, 0x3)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc4204fa000, 0x16, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*Conn).readHandshake(0xc4204fa000, 0xc4200e0316, 0xc4200e0300, 0xb5, 0xb5)
  | /usr/local/go/src/crypto/tls/conn.go:943 +0x8d
  | crypto/tls.(*Conn).clientHandshake(0xc4204fa000, 0x7ca4f0, 0xc4204fa120)
  | /usr/local/go/src/crypto/tls/handshake_client.go:159 +0x97d
  | crypto/tls.(*Conn).Handshake(0xc4204fa000, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1307 +0x1a3
  | net/http.(*Transport).dialConn.func3(0x0, 0xc4204fa000, 0xc4202f8800, 0xc4202555c0)
  | /usr/local/go/src/net/http/transport.go:1082 +0x42
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1087 +0xfec
  |  
  | goroutine 175 [chan receive]:
  | net/http.(*Transport).dialConn(0x963d60, 0x93aa20, 0xc420014240, 0x0, 0xc420019e30, 0x5, 0xc4201410a0, 0x15, 0x73ce60, 0x0, ...)
  | /usr/local/go/src/net/http/transport.go:1088 +0x102e
  | net/http.(*Transport).getConn.func4(0x963d60, 0x93aa20, 0xc420014240, 0xc420220060, 0xc42057bda0)
  | /usr/local/go/src/net/http/transport.go:908 +0x78
  | created by net/http.(*Transport).getConn
  | /usr/local/go/src/net/http/transport.go:910 +0x3a3
  |  
  | goroutine 242 [IO wait]:
  | net.runtime_pollWait(0x7f8383d85880, 0x72, 0xd)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc420052ae8, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc420052ae8, 0xc42040f000, 0x400)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc420052a80, 0xc42040f000, 0x400, 0x400, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc42000e110, 0xc42040f000, 0x400, 0x400, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc420220540, 0x7f8383d41050, 0xc42000e110, 0x5, 0xc42000e110, 0x3)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc4205a4700, 0x16, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*Conn).readHandshake(0xc4205a4700, 0xc42012c116, 0xc42012c180, 0xb5, 0xb5)
  | /usr/local/go/src/crypto/tls/conn.go:943 +0x8d
  | crypto/tls.(*Conn).clientHandshake(0xc4205a4700, 0x7ca4f0, 0xc4205a4820)
  | /usr/local/go/src/crypto/tls/handshake_client.go:159 +0x97d
  | crypto/tls.(*Conn).Handshake(0xc4205a4700, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1307 +0x1a3
  | net/http.(*Transport).dialConn.func3(0x0, 0xc4205a4700, 0xc420117080, 0xc42039c5a0)
  | /usr/local/go/src/net/http/transport.go:1082 +0x42
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1087 +0xfec
  |  
  | goroutine 172 [select]:
  | net/http.setRequestCancel.func3(0x0, 0xc420019cb0, 0xc420116a80, 0xc420015498, 0xc42057b440)
  | /usr/local/go/src/net/http/client.go:320 +0x17c
  | created by net/http.setRequestCancel
  | /usr/local/go/src/net/http/client.go:330 +0x287
  |  
  | goroutine 234 [chan receive]:
  | net/http.(*Transport).getConn.func2.1(0xc42057b500, 0x963d60, 0x7ca000)
  | /usr/local/go/src/net/http/transport.go:897 +0x60
  | created by net/http.(*Transport).getConn.func2
  | /usr/local/go/src/net/http/transport.go:901 +0x7a
  |  
  | goroutine 63 [select]:
  | net/http.(*persistConn).writeLoop(0xc420164240)
  | /usr/local/go/src/net/http/transport.go:1704 +0x43a
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1118 +0xa5a
  |  
  | goroutine 228 [chan receive]:
  | net/http.(*Transport).dialConn(0x963d60, 0x93aa20, 0xc420014240, 0x0, 0xc420019680, 0x5, 0xc420140c20, 0x15, 0x0, 0x0, ...)
  | /usr/local/go/src/net/http/transport.go:1088 +0x102e
  | net/http.(*Transport).getConn.func4(0x963d60, 0x93aa20, 0xc420014240, 0xc420019a40, 0xc42005dd40)
  | /usr/local/go/src/net/http/transport.go:908 +0x78
  | created by net/http.(*Transport).getConn
  | /usr/local/go/src/net/http/transport.go:910 +0x3a3
  |  
  | goroutine 145 [select]:
  | net/http.(*persistConn).roundTrip(0xc420438120, 0xc4201b9100, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/http/transport.go:1898 +0x974
  | net/http.(*Transport).RoundTrip(0x963d60, 0xc4204be500, 0x963d60, 0xed1e60d81, 0x394a8624)
  | /usr/local/go/src/net/http/transport.go:391 +0x74c
  | net/http.send(0xc4204be400, 0x9362e0, 0x963d60, 0xed1e60d81, 0x394a8624, 0x968540, 0x0, 0x8, 0xc42011e080, 0x410c68)
  | /usr/local/go/src/net/http/client.go:249 +0x162
  | net/http.(*Client).send(0xc420019440, 0xc4204be400, 0xed1e60d81, 0x394a8624, 0x968540, 0xc42011e080, 0x0, 0x1, 0x409f0e)
  | /usr/local/go/src/net/http/client.go:173 +0x108
  | net/http.(*Client).Do(0xc420019440, 0xc4204be400, 0xc, 0x7c09b6, 0x21)
  | /usr/local/go/src/net/http/client.go:595 +0x254
  | net/http.(*Client).Post(0xc420019440, 0xc42019cb40, 0x28, 0x7c09b6, 0x21, 0x9368e0, 0xc4201b8fe0, 0x0, 0xc4200d9988, 0x2)
  | /usr/local/go/src/net/http/client.go:720 +0xf8
  | net/http.(*Client).PostForm(0xc420019440, 0xc42019cb40, 0x28, 0xc42019cb10, 0xc, 0xc42019cb40, 0x28)
  | /usr/local/go/src/net/http/client.go:752 +0xdd
  | github.com/99designs/smartling.(*Client).doRequestAndUnmarshalData(0xc420010c80, 0x7b7c15, 0xc, 0x76dde0, 0xc4201b8f60, 0x762820, 0xc42057a840, 0x963d60, 0x93aa20)
  | /go/src/github.com/99designs/smartling/smartling.go:41 +0x2ae
  | github.com/99designs/smartling.(*Client).Status(0xc420010c80, 0xc42033d260, 0x70, 0xc420142298, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/file.go:208 +0x16f
  | github.com/99designs/smartling.(*FaultTolerantClient).Status.func1(0x0, 0x0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:89 +0x7e
  | github.com/99designs/smartling.(*FaultTolerantClient).execWithRetry(0xc420015a30, 0xc42042bcb0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:50 +0x3c
  | github.com/99designs/smartling.(*FaultTolerantClient).Status(0xc420015a30, 0xc42033d260, 0x70, 0xc420142298, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:91 +0xf9
  | main.MustStatus(0xc42033d260, 0x70, 0xc420142298, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:13 +0xa1
  | main.GetProjectStatus.func1(0xc4201422d0, 0xc42019c630, 0xc42033d260, 0x70, 0xc420142298, 0x5)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:65 +0x97
  | created by main.GetProjectStatus
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:66 +0x1a5
  |  
  | goroutine 89 [IO wait]:
  | net.runtime_pollWait(0x7f8383d85d00, 0x72, 0x9)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc42011cd88, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc42011cd88, 0xc4204c9000, 0x1000)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc42011cd20, 0xc4204c9000, 0x1000, 0x1000, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc42011e0a0, 0xc4204c9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc4202951a0, 0x7f8383d41050, 0xc42011e0a0, 0x5, 0xc42011e0a0, 0xc42050e838)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc42047a000, 0x7ca417, 0xc42047a120, 0x452090)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*Conn).Read(0xc42047a000, 0xc420501000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
  | net/http.(*persistConn).Read(0xc420438120, 0xc420501000, 0x1000, 0x1000, 0x5, 0x450520, 0xc4204fc480)
  | /usr/local/go/src/net/http/transport.go:1316 +0x14b
  | bufio.(*Reader).fill(0xc4204a6f00)
  | /usr/local/go/src/bufio/bufio.go:97 +0x117
  | bufio.(*Reader).Peek(0xc4204a6f00, 0x1, 0xc42050ebe5, 0xc420014201, 0x4, 0xc420255140, 0x0)
  | /usr/local/go/src/bufio/bufio.go:129 +0x67
  | net/http.(*persistConn).readLoop(0xc420438120)
  | /usr/local/go/src/net/http/transport.go:1474 +0x196
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1117 +0xa35
  |  
  | goroutine 159 [select]:
  | net/http.setRequestCancel.func3(0x0, 0xc42019cc60, 0xc420116e40, 0xc4201a6938, 0xc42057a900)
  | /usr/local/go/src/net/http/client.go:320 +0x17c
  | created by net/http.setRequestCancel
  | /usr/local/go/src/net/http/client.go:330 +0x287
  |  
  | goroutine 62 [IO wait]:
  | net.runtime_pollWait(0x7f8383d85c40, 0x72, 0xa)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc42025ca78, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc42025ca78, 0xc4204ec000, 0x1000)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc42025ca10, 0xc4204ec000, 0x1000, 0x1000, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc42041a058, 0xc4204ec000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc4202c63c0, 0x7f8383d41050, 0xc42041a058, 0x5, 0xc42041a058, 0xc420513838)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc420478000, 0x7ca417, 0xc420478120, 0x452090)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*Conn).Read(0xc420478000, 0xc42051e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
  | net/http.(*persistConn).Read(0xc420164240, 0xc42051e000, 0x1000, 0x1000, 0x5, 0x450520, 0xc42005df80)
  | /usr/local/go/src/net/http/transport.go:1316 +0x14b
  | bufio.(*Reader).fill(0xc42005de00)
  | /usr/local/go/src/bufio/bufio.go:97 +0x117
  | bufio.(*Reader).Peek(0xc42005de00, 0x1, 0xc420513be5, 0xc420201b01, 0x4, 0xc420255da0, 0x0)
  | /usr/local/go/src/bufio/bufio.go:129 +0x67
  | net/http.(*persistConn).readLoop(0xc420164240)
  | /usr/local/go/src/net/http/transport.go:1474 +0x196
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1117 +0xa35
  |  
  | goroutine 174 [select]:
  | net/http.setRequestCancel.func3(0x0, 0xc420220030, 0xc420116e00, 0xc4200156e8, 0xc42057bb00)
  | /usr/local/go/src/net/http/client.go:320 +0x17c
  | created by net/http.setRequestCancel
  | /usr/local/go/src/net/http/client.go:330 +0x287
  |  
  | goroutine 189 [IO wait]:
  | net.runtime_pollWait(0x7f8383d860c0, 0x72, 0xb)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc420562768, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc420562768, 0xc420595c00, 0x400)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc420562700, 0xc420595c00, 0x400, 0x400, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc420184050, 0xc420595c00, 0x400, 0x400, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc42011b3e0, 0x7f8383d41050, 0xc420184050, 0x5, 0xc420184050, 0xc420037878)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc420473180, 0x7ca417, 0xc4204732a0, 0xc420037a88)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*Conn).Read(0xc420473180, 0xc420079000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
  | net/http.(*persistConn).Read(0xc4204399e0, 0xc420079000, 0x1000, 0x1000, 0xc420037b60, 0xa, 0xc420037b80)
  | /usr/local/go/src/net/http/transport.go:1316 +0x14b
  | bufio.(*Reader).fill(0xc42005c600)
  | /usr/local/go/src/bufio/bufio.go:97 +0x117
  | bufio.(*Reader).Peek(0xc42005c600, 0x1, 0xc42005c660, 0xc4204e0480, 0xc420192100, 0x0, 0xc420384800)
  | /usr/local/go/src/bufio/bufio.go:129 +0x67
  | net/http.(*persistConn).readLoop(0xc4204399e0)
  | /usr/local/go/src/net/http/transport.go:1474 +0x196
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1117 +0xa35
  |  
  | goroutine 111 [select]:
  | net/http.(*persistConn).roundTrip(0xc42018f8c0, 0xc420140e20, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/http/transport.go:1898 +0x974
  | net/http.(*Transport).RoundTrip(0x963d60, 0xc420108800, 0x963d60, 0xed1e60d82, 0x10675821)
  | /usr/local/go/src/net/http/transport.go:391 +0x74c
  | net/http.send(0xc420108700, 0x9362e0, 0x963d60, 0xed1e60d82, 0x10675821, 0x968540, 0x0, 0x8, 0xc42000e0d0, 0x410c68)
  | /usr/local/go/src/net/http/client.go:249 +0x162
  | net/http.(*Client).send(0xc420019440, 0xc420108700, 0xed1e60d82, 0x10675821, 0x968540, 0xc42000e0d0, 0x0, 0x1, 0x409f0e)
  | /usr/local/go/src/net/http/client.go:173 +0x108
  | net/http.(*Client).Do(0xc420019440, 0xc420108700, 0xc, 0x7c09b6, 0x21)
  | /usr/local/go/src/net/http/client.go:595 +0x254
  | net/http.(*Client).Post(0xc420019440, 0xc420019ad0, 0x28, 0x7c09b6, 0x21, 0x9368e0, 0xc420140ca0, 0x0, 0xc420033988, 0x2)
  | /usr/local/go/src/net/http/client.go:720 +0xf8
  | net/http.(*Client).PostForm(0xc420019440, 0xc420019ad0, 0x28, 0xc420019a70, 0xc, 0xc420019ad0, 0x28)
  | /usr/local/go/src/net/http/client.go:752 +0xdd
  | github.com/99designs/smartling.(*Client).doRequestAndUnmarshalData(0xc420010c80, 0x7b7c15, 0xc, 0x76dde0, 0xc420140c40, 0x762820, 0xc42057b2c0, 0xc4204ca9c0, 0x300000002)
  | /go/src/github.com/99designs/smartling/smartling.go:41 +0x2ae
  | github.com/99designs/smartling.(*Client).Status(0xc420010c80, 0xc4204fd200, 0x5b, 0xc420142267, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/file.go:208 +0x16f
  | github.com/99designs/smartling.(*FaultTolerantClient).Status.func1(0x0, 0x0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:89 +0x7e
  | github.com/99designs/smartling.(*FaultTolerantClient).execWithRetry(0xc420015a30, 0xc420585cb0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:50 +0x3c
  | github.com/99designs/smartling.(*FaultTolerantClient).Status(0xc420015a30, 0xc4204fd200, 0x5b, 0xc420142267, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:91 +0xf9
  | main.MustStatus(0xc4204fd200, 0x5b, 0xc420142267, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:13 +0xa1
  | main.GetProjectStatus.func1(0xc4201422d0, 0xc42019c630, 0xc4204fd200, 0x5b, 0xc420142267, 0x5)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:65 +0x97
  | created by main.GetProjectStatus
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:66 +0x1a5
  |  
  | goroutine 198 [runnable]:
  | syscall.Syscall(0x1, 0x7, 0xc420356c80, 0x7e, 0x7e, 0x7e, 0x0)
  | /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
  | syscall.write(0x7, 0xc420356c80, 0x7e, 0xa0, 0x77, 0x0, 0x0)
  | /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1064 +0x55
  | syscall.Write(0x7, 0xc420356c80, 0x7e, 0xa0, 0xc, 0x100000000000010, 0x18)
  | /usr/local/go/src/syscall/syscall_unix.go:181 +0x49
  | net.(*netFD).Write(0xc420563260, 0xc420356c80, 0x7e, 0xa0, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/fd_unix.go:332 +0x15e
  | net.(*conn).Write(0xc42041a000, 0xc420356c80, 0x7e, 0xa0, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:193 +0x70
  | crypto/tls.(*Conn).flush(0xc42053b880, 0xc42053b969, 0xc, 0xc)
  | /usr/local/go/src/crypto/tls/conn.go:842 +0x64
  | crypto/tls.(*Conn).clientHandshake(0xc42053b880, 0x7ca4f0, 0xc42053b9a0)
  | /usr/local/go/src/crypto/tls/handshake_client.go:237 +0x1024
  | crypto/tls.(*Conn).Handshake(0xc42053b880, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1307 +0x1a3
  | net/http.(*Transport).dialConn.func3(0x0, 0xc42053b880, 0xc4203a0c00, 0xc4204a5440)
  | /usr/local/go/src/net/http/transport.go:1082 +0x42
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1087 +0xfec
  |  
  | goroutine 227 [chan receive]:
  | net/http.(*Transport).dialConn(0x963d60, 0x93aa20, 0xc420014240, 0x0, 0xc4201f8870, 0x5, 0xc420192780, 0x15, 0x0, 0x0, ...)
  | /usr/local/go/src/net/http/transport.go:1088 +0x102e
  | net/http.(*Transport).getConn.func4(0x963d60, 0x93aa20, 0xc420014240, 0xc4201f8a80, 0xc42005d4a0)
  | /usr/local/go/src/net/http/transport.go:908 +0x78
  | created by net/http.(*Transport).getConn
  | /usr/local/go/src/net/http/transport.go:910 +0x3a3
  |  
  | goroutine 211 [select]:
  | net/http.setRequestCancel.func3(0x0, 0xc42019d6e0, 0xc420214740, 0xc42011935c, 0xc420110180)
  | /usr/local/go/src/net/http/client.go:320 +0x17c
  | created by net/http.setRequestCancel
  | /usr/local/go/src/net/http/client.go:330 +0x287
  |  
  | goroutine 243 [chan receive]:
  | net/http.(*Transport).getConn.func2.1(0xc420110600, 0x963d60, 0x7ca000)
  | /usr/local/go/src/net/http/transport.go:897 +0x60
  | created by net/http.(*Transport).getConn.func2
  | /usr/local/go/src/net/http/transport.go:901 +0x7a
  |  
  | goroutine 226 [select]:
  | net/http.setRequestCancel.func3(0x0, 0xc4201f8a50, 0xc4202f8380, 0xc42014263c, 0xc42005d3e0)
  | /usr/local/go/src/net/http/client.go:320 +0x17c
  | created by net/http.setRequestCancel
  | /usr/local/go/src/net/http/client.go:330 +0x287
  |  
  | goroutine 141 [select]:
  | net/http.(*persistConn).roundTrip(0xc420164240, 0xc4201b8e80, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/http/transport.go:1898 +0x974
  | net/http.(*Transport).RoundTrip(0x963d60, 0xc4204be300, 0x963d60, 0xed1e60d81, 0x3948b083)
  | /usr/local/go/src/net/http/transport.go:391 +0x74c
  | net/http.send(0xc4204be200, 0x9362e0, 0x963d60, 0xed1e60d81, 0x3948b083, 0x968540, 0x0, 0x8, 0xc42011e058, 0x410c68)
  | /usr/local/go/src/net/http/client.go:249 +0x162
  | net/http.(*Client).send(0xc420019440, 0xc4204be200, 0xed1e60d81, 0x3948b083, 0x968540, 0xc42011e058, 0x0, 0x1, 0x409f0e)
  | /usr/local/go/src/net/http/client.go:173 +0x108
  | net/http.(*Client).Do(0xc420019440, 0xc4204be200, 0xc, 0x7c09b6, 0x21)
  | /usr/local/go/src/net/http/client.go:595 +0x254
  | net/http.(*Client).Post(0xc420019440, 0xc42019c8d0, 0x28, 0x7c09b6, 0x21, 0x9368e0, 0xc4201b8d40, 0x0, 0xc4200d9988, 0x2)
  | /usr/local/go/src/net/http/client.go:720 +0xf8
  | net/http.(*Client).PostForm(0xc420019440, 0xc42019c8d0, 0x28, 0xc42019c8a0, 0xc, 0xc42019c8d0, 0x28)
  | /usr/local/go/src/net/http/client.go:752 +0xdd
  | github.com/99designs/smartling.(*Client).doRequestAndUnmarshalData(0xc420010c80, 0x7b7c15, 0xc, 0x76dde0, 0xc4201b8ce0, 0x762820, 0xc42005dda0, 0x963d60, 0x93aa20)
  | /go/src/github.com/99designs/smartling/smartling.go:41 +0x2ae
  | github.com/99designs/smartling.(*Client).Status(0xc420010c80, 0xc42033d260, 0x70, 0xc42014222a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/file.go:208 +0x16f
  | github.com/99designs/smartling.(*FaultTolerantClient).Status.func1(0x2, 0xc420023458)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:89 +0x7e
  | github.com/99designs/smartling.(*FaultTolerantClient).execWithRetry(0xc420015a30, 0xc42043dcb0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:50 +0x3c
  | github.com/99designs/smartling.(*FaultTolerantClient).Status(0xc420015a30, 0xc42033d260, 0x70, 0xc42014222a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:91 +0xf9
  | main.MustStatus(0xc42033d260, 0x70, 0xc42014222a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:13 +0xa1
  | main.GetProjectStatus.func1(0xc4201422d0, 0xc42019c630, 0xc42033d260, 0x70, 0xc42014222a, 0x5)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:65 +0x97
  | created by main.GetProjectStatus
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:66 +0x1a5
  |  
  | goroutine 213 [chan receive]:
  | net/http.(*Transport).dialConn(0x963d60, 0x93aa20, 0xc420014240, 0x0, 0xc42019d7d0, 0x5, 0xc4201ae5e0, 0x15, 0x180001, 0x0, ...)
  | /usr/local/go/src/net/http/transport.go:1088 +0x102e
  | net/http.(*Transport).getConn.func4(0x963d60, 0x93aa20, 0xc420014240, 0xc42019d8f0, 0xc420110600)
  | /usr/local/go/src/net/http/transport.go:908 +0x78
  | created by net/http.(*Transport).getConn
  | /usr/local/go/src/net/http/transport.go:910 +0x3a3
  |  
  | goroutine 135 [IO wait]:
  | net.runtime_pollWait(0x7f8383d85940, 0x72, 0xe)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc42011d258, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc42011d258, 0xc4204ab000, 0x400)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc42011d1f0, 0xc4204ab000, 0x400, 0x400, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc4201840e8, 0xc4204ab000, 0x400, 0x400, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc420271680, 0x7f8383d41050, 0xc4201840e8, 0x5, 0xc4201840e8, 0xc420577838)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc420596000, 0x7ca417, 0xc420596120, 0x452090)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*Conn).Read(0xc420596000, 0xc4203ae000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
  | net/http.(*persistConn).Read(0xc420438240, 0xc4203ae000, 0x1000, 0x1000, 0x5, 0x450520, 0xc4204a41e0)
  | /usr/local/go/src/net/http/transport.go:1316 +0x14b
  | bufio.(*Reader).fill(0xc4204a4060)
  | /usr/local/go/src/bufio/bufio.go:97 +0x117
  | bufio.(*Reader).Peek(0xc4204a4060, 0x1, 0xc420577be5, 0xc420118001, 0x4, 0xc4204a40c0, 0x0)
  | /usr/local/go/src/bufio/bufio.go:129 +0x67
  | net/http.(*persistConn).readLoop(0xc420438240)
  | /usr/local/go/src/net/http/transport.go:1474 +0x196
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1117 +0xa35
  |  
  | goroutine 210 [select]:
  | net/http.(*Transport).getConn(0x963d60, 0xc420192a40, 0x0, 0xc4201f8e40, 0x5, 0xc420192a80, 0x15, 0x0, 0x0, 0x18)
  | /usr/local/go/src/net/http/transport.go:913 +0xb92
  | net/http.(*Transport).RoundTrip(0x963d60, 0xc420424700, 0x963d60, 0xed1e60d82, 0x106ac2a0)
  | /usr/local/go/src/net/http/transport.go:378 +0x58c
  | net/http.send(0xc420424600, 0x9362e0, 0x963d60, 0xed1e60d82, 0x106ac2a0, 0x968540, 0x0, 0x8, 0xc4201840a0, 0x410c68)
  | /usr/local/go/src/net/http/client.go:249 +0x162
  | net/http.(*Client).send(0xc420019440, 0xc420424600, 0xed1e60d82, 0x106ac2a0, 0x968540, 0xc4201840a0, 0x0, 0x1, 0x409f0e)
  | /usr/local/go/src/net/http/client.go:173 +0x108
  | net/http.(*Client).Do(0xc420019440, 0xc420424600, 0xc, 0x7c09b6, 0x21)
  | /usr/local/go/src/net/http/client.go:595 +0x254
  | net/http.(*Client).Post(0xc420019440, 0xc4201f8e40, 0x28, 0x7c09b6, 0x21, 0x9368e0, 0xc420192900, 0x0, 0xc420416988, 0x2)
  | /usr/local/go/src/net/http/client.go:720 +0xf8
  | net/http.(*Client).PostForm(0xc420019440, 0xc4201f8e40, 0x28, 0xc4201f8de0, 0xc, 0xc4201f8e40, 0x28)
  | /usr/local/go/src/net/http/client.go:752 +0xdd
  | github.com/99designs/smartling.(*Client).doRequestAndUnmarshalData(0xc420010c80, 0x7b7c15, 0xc, 0x76dde0, 0xc4201928c0, 0x762820, 0xc4202543c0, 0x0, 0x0)
  | /go/src/github.com/99designs/smartling/smartling.go:41 +0x2ae
  | github.com/99designs/smartling.(*Client).Status(0xc420010c80, 0xc4204fd200, 0x5b, 0xc42014229e, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/file.go:208 +0x16f
  | github.com/99designs/smartling.(*FaultTolerantClient).Status.func1(0x0, 0xc4204b5598)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:89 +0x7e
  | github.com/99designs/smartling.(*FaultTolerantClient).execWithRetry(0xc420015a30, 0xc420043cb0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:50 +0x3c
  | github.com/99designs/smartling.(*FaultTolerantClient).Status(0xc420015a30, 0xc4204fd200, 0x5b, 0xc42014229e, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:91 +0xf9
  | main.MustStatus(0xc4204fd200, 0x5b, 0xc42014229e, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:13 +0xa1
  | main.GetProjectStatus.func1(0xc4201422d0, 0xc42019c630, 0xc4204fd200, 0x5b, 0xc42014229e, 0x2)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:65 +0x97
  | created by main.GetProjectStatus
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:66 +0x1a5
  |  
  | goroutine 110 [select]:
  | net/http.(*persistConn).roundTrip(0xc4204399e0, 0xc4201924e0, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/http/transport.go:1898 +0x974
  | net/http.(*Transport).RoundTrip(0x963d60, 0xc420424100, 0x963d60, 0xed1e60d82, 0x1066b9ea)
  | /usr/local/go/src/net/http/transport.go:391 +0x74c
  | net/http.send(0xc420424000, 0x9362e0, 0x963d60, 0xed1e60d82, 0x1066b9ea, 0x968540, 0x0, 0x8, 0xc420184048, 0x410c68)
  | /usr/local/go/src/net/http/client.go:249 +0x162
  | net/http.(*Client).send(0xc420019440, 0xc420424000, 0xed1e60d82, 0x1066b9ea, 0x968540, 0xc420184048, 0x0, 0x1, 0x409f0e)
  | /usr/local/go/src/net/http/client.go:173 +0x108
  | net/http.(*Client).Do(0xc420019440, 0xc420424000, 0xc, 0x7c09b6, 0x21)
  | /usr/local/go/src/net/http/client.go:595 +0x254
  | net/http.(*Client).Post(0xc420019440, 0xc4201f85d0, 0x28, 0x7c09b6, 0x21, 0x9368e0, 0xc4201923a0, 0x0, 0xc420449988, 0x2)
  | /usr/local/go/src/net/http/client.go:720 +0xf8
  | net/http.(*Client).PostForm(0xc420019440, 0xc4201f85d0, 0x28, 0xc4201f85a0, 0xc, 0xc4201f85d0, 0x28)
  | /usr/local/go/src/net/http/client.go:752 +0xdd
  | github.com/99designs/smartling.(*Client).doRequestAndUnmarshalData(0xc420010c80, 0x7b7c15, 0xc, 0x76dde0, 0xc420192360, 0x762820, 0xc42005c7e0, 0x2, 0x3f3)
  | /go/src/github.com/99designs/smartling/smartling.go:41 +0x2ae
  | github.com/99designs/smartling.(*Client).Status(0xc420010c80, 0xc4204fd200, 0x5b, 0xc420142249, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/file.go:208 +0x16f
  | github.com/99designs/smartling.(*FaultTolerantClient).Status.func1(0x0, 0x0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:89 +0x7e
  | github.com/99designs/smartling.(*FaultTolerantClient).execWithRetry(0xc420015a30, 0xc420449cb0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:50 +0x3c
  | github.com/99designs/smartling.(*FaultTolerantClient).Status(0xc420015a30, 0xc4204fd200, 0x5b, 0xc420142249, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:91 +0xf9
  | main.MustStatus(0xc4204fd200, 0x5b, 0xc420142249, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:13 +0xa1
  | main.GetProjectStatus.func1(0xc4201422d0, 0xc42019c630, 0xc4204fd200, 0x5b, 0xc420142249, 0x5)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:65 +0x97
  | created by main.GetProjectStatus
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:66 +0x1a5
  |  
  | goroutine 153 [select]:
  | net/http.(*persistConn).writeLoop(0xc420076c60)
  | /usr/local/go/src/net/http/transport.go:1704 +0x43a
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1118 +0xa5a
  |  
  | goroutine 230 [chan receive]:
  | net/http.(*Transport).dialConn(0x963d60, 0x93aa20, 0xc420014240, 0x0, 0xc4201f8e40, 0x5, 0xc420192a80, 0x15, 0x0, 0x0, ...)
  | /usr/local/go/src/net/http/transport.go:1088 +0x102e
  | net/http.(*Transport).getConn.func4(0x963d60, 0x93aa20, 0xc420014240, 0xc4201f9290, 0xc420254840)
  | /usr/local/go/src/net/http/transport.go:908 +0x78
  | created by net/http.(*Transport).getConn
  | /usr/local/go/src/net/http/transport.go:910 +0x3a3
  |  
  | goroutine 219 [IO wait]:
  | net.runtime_pollWait(0x7f8383d85700, 0x72, 0xc)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc42025c848, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc42025c848, 0xc4204ebc00, 0x400)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc42025c7e0, 0xc4204ebc00, 0x400, 0x400, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc42011e1b0, 0xc4204ebc00, 0x400, 0x400, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc4202700f0, 0x7f8383d41050, 0xc42011e1b0, 0x5, 0xc42011e1b0, 0x3)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc420597180, 0x16, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*Conn).readHandshake(0xc420597180, 0xc4200c2216, 0xc4200c2240, 0xb5, 0xb5)
  | /usr/local/go/src/crypto/tls/conn.go:943 +0x8d
  | crypto/tls.(*Conn).clientHandshake(0xc420597180, 0x7ca4f0, 0xc4205972a0)
  | /usr/local/go/src/crypto/tls/handshake_client.go:159 +0x97d
  | crypto/tls.(*Conn).Handshake(0xc420597180, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1307 +0x1a3
  | net/http.(*Transport).dialConn.func3(0x0, 0xc420597180, 0xc420214d00, 0xc4201117a0)
  | /usr/local/go/src/net/http/transport.go:1082 +0x42
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1087 +0xfec
  |  
  | goroutine 103 [select]:
  | net/http.setRequestCancel.func3(0x0, 0xc4201c6d50, 0xc4201c3400, 0xc4201b53cc, 0xc420111500)
  | /usr/local/go/src/net/http/client.go:320 +0x17c
  | created by net/http.setRequestCancel
  | /usr/local/go/src/net/http/client.go:330 +0x287
  |  
  | goroutine 112 [select]:
  | net/http.(*Transport).getConn(0x963d60, 0xc420140be0, 0x0, 0xc420019680, 0x5, 0xc420140c20, 0x15, 0x0, 0x0, 0x18)
  | /usr/local/go/src/net/http/transport.go:913 +0xb92
  | net/http.(*Transport).RoundTrip(0x963d60, 0xc420108600, 0x963d60, 0xed1e60d82, 0x1066ccb8)
  | /usr/local/go/src/net/http/transport.go:378 +0x58c
  | net/http.send(0xc420108300, 0x9362e0, 0x963d60, 0xed1e60d82, 0x1066ccb8, 0x968540, 0x0, 0x8, 0xc42000e040, 0x410c68)
  | /usr/local/go/src/net/http/client.go:249 +0x162
  | net/http.(*Client).send(0xc420019440, 0xc420108300, 0xed1e60d82, 0x1066ccb8, 0x968540, 0xc42000e040, 0x0, 0x1, 0x409f0e)
  | /usr/local/go/src/net/http/client.go:173 +0x108
  | net/http.(*Client).Do(0xc420019440, 0xc420108300, 0xc, 0x7c09b6, 0x21)
  | /usr/local/go/src/net/http/client.go:595 +0x254
  | net/http.(*Client).Post(0xc420019440, 0xc420019680, 0x28, 0x7c09b6, 0x21, 0x9368e0, 0xc420140ac0, 0x0, 0xc42043f988, 0x2)
  | /usr/local/go/src/net/http/client.go:720 +0xf8
  | net/http.(*Client).PostForm(0xc420019440, 0xc420019680, 0x28, 0xc420019650, 0xc, 0xc420019680, 0x28)
  | /usr/local/go/src/net/http/client.go:752 +0xdd
  | github.com/99designs/smartling.(*Client).doRequestAndUnmarshalData(0xc420010c80, 0x7b7c15, 0xc, 0x76dde0, 0xc420140a80, 0x762820, 0xc42057b080, 0xc4204ca9c0, 0x300000002)
  | /go/src/github.com/99designs/smartling/smartling.go:41 +0x2ae
  | github.com/99designs/smartling.(*Client).Status(0xc420010c80, 0xc4204fd200, 0x5b, 0xc420142288, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/file.go:208 +0x16f
  | github.com/99designs/smartling.(*FaultTolerantClient).Status.func1(0xc4204b4208, 0x0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:89 +0x7e
  | github.com/99designs/smartling.(*FaultTolerantClient).execWithRetry(0xc420015a30, 0xc42043fcb0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:50 +0x3c
  | github.com/99designs/smartling.(*FaultTolerantClient).Status(0xc420015a30, 0xc4204fd200, 0x5b, 0xc420142288, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:91 +0xf9
  | main.MustStatus(0xc4204fd200, 0x5b, 0xc420142288, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:13 +0xa1
  | main.GetProjectStatus.func1(0xc4201422d0, 0xc42019c630, 0xc4204fd200, 0x5b, 0xc420142288, 0x5)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:65 +0x97
  | created by main.GetProjectStatus
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:66 +0x1a5
  |  
  | goroutine 152 [IO wait]:
  | net.runtime_pollWait(0x7f8383d857c0, 0x72, 0x10)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc42011d2c8, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc42011d2c8, 0xc420594c00, 0x400)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc42011d260, 0xc420594c00, 0x400, 0x400, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc42000e2c8, 0xc420594c00, 0x400, 0x400, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc4201f98c0, 0x7f8383d41050, 0xc42000e2c8, 0x5, 0xc42000e2c8, 0xc42016c838)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc420472700, 0x7ca417, 0xc420472820, 0x452090)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*Conn).Read(0xc420472700, 0xc4204a8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
  | net/http.(*persistConn).Read(0xc420076c60, 0xc4204a8000, 0x1000, 0x1000, 0x5, 0x450520, 0xc42005d380)
  | /usr/local/go/src/net/http/transport.go:1316 +0x14b
  | bufio.(*Reader).fill(0xc42005cf60)
  | /usr/local/go/src/bufio/bufio.go:97 +0x117
  | bufio.(*Reader).Peek(0xc42005cf60, 0x1, 0xc42016cbe5, 0xc420142e01, 0x4, 0xc420110c00, 0x0)
  | /usr/local/go/src/bufio/bufio.go:129 +0x67
  | net/http.(*persistConn).readLoop(0xc420076c60)
  | /usr/local/go/src/net/http/transport.go:1474 +0x196
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1117 +0xa35
  |  
  | goroutine 113 [select]:
  | net/http.(*persistConn).roundTrip(0xc4200777a0, 0xc4201ae5a0, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/http/transport.go:1898 +0x974
  | net/http.(*Transport).RoundTrip(0x963d60, 0xc4204beb00, 0x963d60, 0xed1e60d82, 0x10681aab)
  | /usr/local/go/src/net/http/transport.go:391 +0x74c
  | net/http.send(0xc4204bea00, 0x9362e0, 0x963d60, 0xed1e60d82, 0x10681aab, 0x968540, 0x0, 0x8, 0xc42011e198, 0x410c68)
  | /usr/local/go/src/net/http/client.go:249 +0x162
  | net/http.(*Client).send(0xc420019440, 0xc4204bea00, 0xed1e60d82, 0x10681aab, 0x968540, 0xc42011e198, 0x0, 0x1, 0x409f0e)
  | /usr/local/go/src/net/http/client.go:173 +0x108
  | net/http.(*Client).Do(0xc420019440, 0xc4204bea00, 0xc, 0x7c09b6, 0x21)
  | /usr/local/go/src/net/http/client.go:595 +0x254
  | net/http.(*Client).Post(0xc420019440, 0xc42019d7d0, 0x28, 0x7c09b6, 0x21, 0x9368e0, 0xc4201ae480, 0x0, 0xc420518988, 0x2)
  | /usr/local/go/src/net/http/client.go:720 +0xf8
  | net/http.(*Client).PostForm(0xc420019440, 0xc42019d7d0, 0x28, 0xc42019d7a0, 0xc, 0xc42019d7d0, 0x28)
  | /usr/local/go/src/net/http/client.go:752 +0xdd
  | github.com/99designs/smartling.(*Client).doRequestAndUnmarshalData(0xc420010c80, 0x7b7c15, 0xc, 0x76dde0, 0xc4201ae440, 0x762820, 0xc4201103c0, 0x0, 0x0)
  | /go/src/github.com/99designs/smartling/smartling.go:41 +0x2ae
  | github.com/99designs/smartling.(*Client).Status(0xc420010c80, 0xc4204fd200, 0x5b, 0xc420142298, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/file.go:208 +0x16f
  | github.com/99designs/smartling.(*FaultTolerantClient).Status.func1(0x1, 0x0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:89 +0x7e
  | github.com/99designs/smartling.(*FaultTolerantClient).execWithRetry(0xc420015a30, 0xc420049cb0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:50 +0x3c
  | github.com/99designs/smartling.(*FaultTolerantClient).Status(0xc420015a30, 0xc4204fd200, 0x5b, 0xc420142298, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:91 +0xf9
  | main.MustStatus(0xc4204fd200, 0x5b, 0xc420142298, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:13 +0xa1
  | main.GetProjectStatus.func1(0xc4201422d0, 0xc42019c630, 0xc4204fd200, 0x5b, 0xc420142298, 0x5)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:65 +0x97
  | created by main.GetProjectStatus
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:66 +0x1a5
  |  
  | goroutine 108 [select]:
  | net/http.(*persistConn).roundTrip(0xc420076c60, 0xc420192740, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/http/transport.go:1898 +0x974
  | net/http.(*Transport).RoundTrip(0x963d60, 0xc420424300, 0x963d60, 0xed1e60d82, 0x1068a3b8)
  | /usr/local/go/src/net/http/transport.go:391 +0x74c
  | net/http.send(0xc420424200, 0x9362e0, 0x963d60, 0xed1e60d82, 0x1068a3b8, 0x968540, 0x0, 0x8, 0xc420184078, 0x410c68)
  | /usr/local/go/src/net/http/client.go:249 +0x162
  | net/http.(*Client).send(0xc420019440, 0xc420424200, 0xed1e60d82, 0x1068a3b8, 0x968540, 0xc420184078, 0x0, 0x1, 0x409f0e)
  | /usr/local/go/src/net/http/client.go:173 +0x108
  | net/http.(*Client).Do(0xc420019440, 0xc420424200, 0xc, 0x7c09b6, 0x21)
  | /usr/local/go/src/net/http/client.go:595 +0x254
  | net/http.(*Client).Post(0xc420019440, 0xc4201f8870, 0x28, 0x7c09b6, 0x21, 0x9368e0, 0xc420192600, 0x0, 0xc420414988, 0x2)
  | /usr/local/go/src/net/http/client.go:720 +0xf8
  | net/http.(*Client).PostForm(0xc420019440, 0xc4201f8870, 0x28, 0xc4201f8810, 0xc, 0xc4201f8870, 0x28)
  | /usr/local/go/src/net/http/client.go:752 +0xdd
  | github.com/99designs/smartling.(*Client).doRequestAndUnmarshalData(0xc420010c80, 0x7b7c15, 0xc, 0x76dde0, 0xc4201925a0, 0x762820, 0xc42005cb40, 0x963d60, 0x93aa20)
  | /go/src/github.com/99designs/smartling/smartling.go:41 +0x2ae
  | github.com/99designs/smartling.(*Client).Status(0xc420010c80, 0xc4204fd200, 0x5b, 0xc420142208, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/file.go:208 +0x16f
  | github.com/99designs/smartling.(*FaultTolerantClient).Status.func1(0x0, 0x0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:89 +0x7e
  | github.com/99designs/smartling.(*FaultTolerantClient).execWithRetry(0xc420015a30, 0xc42042dcb0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:50 +0x3c
  | github.com/99designs/smartling.(*FaultTolerantClient).Status(0xc420015a30, 0xc4204fd200, 0x5b, 0xc420142208, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:91 +0xf9
  | main.MustStatus(0xc4204fd200, 0x5b, 0xc420142208, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:13 +0xa1
  | main.GetProjectStatus.func1(0xc4201422d0, 0xc42019c630, 0xc4204fd200, 0x5b, 0xc420142208, 0x5)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:65 +0x97
  | created by main.GetProjectStatus
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:66 +0x1a5
  |  
  | goroutine 136 [select]:
  | net/http.(*persistConn).writeLoop(0xc420438240)
  | /usr/local/go/src/net/http/transport.go:1704 +0x43a
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1118 +0xa5a
  |  
  | goroutine 190 [select]:
  | net/http.(*persistConn).writeLoop(0xc4204399e0)
  | /usr/local/go/src/net/http/transport.go:1704 +0x43a
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1118 +0xa5a
  |  
  | goroutine 167 [IO wait]:
  | net.runtime_pollWait(0x7f8383d85b80, 0x72, 0x5)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc420562618, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc420562618, 0xc42047c000, 0x400)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc4205625b0, 0xc42047c000, 0x400, 0x400, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc42000e0a8, 0xc42047c000, 0x400, 0x400, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc4201c73e0, 0x7f8383d41050, 0xc42000e0a8, 0x5, 0xc42000e0a8, 0xc420519838)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc4204fb500, 0x7ca417, 0xc4204fb620, 0x452090)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*Conn).Read(0xc4204fb500, 0xc42059a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
  | net/http.(*persistConn).Read(0xc42018f8c0, 0xc42059a000, 0x1000, 0x1000, 0x5, 0x450520, 0xc42057a7e0)
  | /usr/local/go/src/net/http/transport.go:1316 +0x14b
  | bufio.(*Reader).fill(0xc42057a240)
  | /usr/local/go/src/bufio/bufio.go:97 +0x117
  | bufio.(*Reader).Peek(0xc42057a240, 0x1, 0xc420519be5, 0xc4201dee01, 0x4, 0xc42057a4e0, 0x0)
  | /usr/local/go/src/bufio/bufio.go:129 +0x67
  | net/http.(*persistConn).readLoop(0xc42018f8c0)
  | /usr/local/go/src/net/http/transport.go:1474 +0x196
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1117 +0xa35
  |  
  | goroutine 109 [select]:
  | net/http.(*Transport).getConn(0x963d60, 0xc420141060, 0x0, 0xc420019e30, 0x5, 0xc4201410a0, 0x15, 0x0, 0x0, 0x18)
  | /usr/local/go/src/net/http/transport.go:913 +0xb92
  | net/http.(*Transport).RoundTrip(0x963d60, 0xc420108a00, 0x963d60, 0xed1e60d82, 0x10698066)
  | /usr/local/go/src/net/http/transport.go:378 +0x58c
  | net/http.send(0xc420108900, 0x9362e0, 0x963d60, 0xed1e60d82, 0x10698066, 0x968540, 0x0, 0x8, 0xc42000e0f8, 0x410c68)
  | /usr/local/go/src/net/http/client.go:249 +0x162
  | net/http.(*Client).send(0xc420019440, 0xc420108900, 0xed1e60d82, 0x10698066, 0x968540, 0xc42000e0f8, 0x0, 0x1, 0x409f0e)
  | /usr/local/go/src/net/http/client.go:173 +0x108
  | net/http.(*Client).Do(0xc420019440, 0xc420108900, 0xc, 0x7c09b6, 0x21)
  | /usr/local/go/src/net/http/client.go:595 +0x254
  | net/http.(*Client).Post(0xc420019440, 0xc420019e30, 0x28, 0x7c09b6, 0x21, 0x9368e0, 0xc420140f60, 0x0, 0xc420033988, 0x2)
  | /usr/local/go/src/net/http/client.go:720 +0xf8
  | net/http.(*Client).PostForm(0xc420019440, 0xc420019e30, 0x28, 0xc420019e00, 0xc, 0xc420019e30, 0x28)
  | /usr/local/go/src/net/http/client.go:752 +0xdd
  | github.com/99designs/smartling.(*Client).doRequestAndUnmarshalData(0xc420010c80, 0x7b7c15, 0xc, 0x76dde0, 0xc420140f00, 0x762820, 0xc42057b980, 0x963d60, 0x93aa20)
  | /go/src/github.com/99designs/smartling/smartling.go:41 +0x2ae
  | github.com/99designs/smartling.(*Client).Status(0xc420010c80, 0xc4204fd200, 0x5b, 0xc42014222a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/file.go:208 +0x16f
  | github.com/99designs/smartling.(*FaultTolerantClient).Status.func1(0x0, 0x0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:89 +0x7e
  | github.com/99designs/smartling.(*FaultTolerantClient).execWithRetry(0xc420015a30, 0xc420583cb0)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:50 +0x3c
  | github.com/99designs/smartling.(*FaultTolerantClient).Status(0xc420015a30, 0xc4204fd200, 0x5b, 0xc42014222a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/faulttolerant.go:91 +0xf9
  | main.MustStatus(0xc4204fd200, 0x5b, 0xc42014222a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:13 +0xa1
  | main.GetProjectStatus.func1(0xc4201422d0, 0xc42019c630, 0xc4204fd200, 0x5b, 0xc42014222a, 0x5)
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:65 +0x97
  | created by main.GetProjectStatus
  | /go/src/github.com/99designs/smartling/cli/smartling/status.go:66 +0x1a5
  |  
  | goroutine 220 [IO wait]:
  | net.runtime_pollWait(0x7f8383d85ac0, 0x72, 0xf)
  | /usr/local/go/src/runtime/netpoll.go:164 +0x59
  | net.(*pollDesc).wait(0xc4205633a8, 0x72, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
  | net.(*pollDesc).waitRead(0xc4205633a8, 0xc4204c0000, 0x1000)
  | /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
  | net.(*netFD).Read(0xc420563340, 0xc4204c0000, 0x1000, 0x1000, 0x0, 0x937920, 0x9344b8)
  | /usr/local/go/src/net/fd_unix.go:250 +0x1b7
  | net.(*conn).Read(0xc42011e1b8, 0xc4204c0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  | /usr/local/go/src/net/net.go:181 +0x70
  | crypto/tls.(*block).readFromUntil(0xc4202205d0, 0x7f8383d41050, 0xc42011e1b8, 0x5, 0xc42011e1b8, 0x3f3)
  | /usr/local/go/src/crypto/tls/conn.go:488 +0x98
  | crypto/tls.(*Conn).readRecord(0xc420597500, 0xc420267114, 0xc420543b00, 0xc420543b78)
  | /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
  | crypto/tls.(*clientHandshakeState).readFinished(0xc420543e50, 0xc4205975f5, 0xc, 0xc, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/handshake_client.go:584 +0x53
  | crypto/tls.(*Conn).clientHandshake(0xc420597500, 0x7ca4f0, 0xc420597620)
  | /usr/local/go/src/crypto/tls/handshake_client.go:244 +0x109f
  | crypto/tls.(*Conn).Handshake(0xc420597500, 0x0, 0x0)
  | /usr/local/go/src/crypto/tls/conn.go:1307 +0x1a3
  | net/http.(*Transport).dialConn.func3(0x0, 0xc420597500, 0xc420214dc0, 0xc420111c20)
  | /usr/local/go/src/net/http/transport.go:1082 +0x42
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1087 +0xfec
  |  
  | goroutine 196 [select]:
  | net/http.(*persistConn).writeLoop(0xc420077320)
  | /usr/local/go/src/net/http/transport.go:1704 +0x43a
  | created by net/http.(*Transport).dialConn
  | /usr/local/go/src/net/http/transport.go:1118 +0xa5a


```

### PR DESCRIPTION
**Pull request by navitronic**
This might fix #13.

Uses locking provided by `sync.RWMutex` to protect against concurrent reads and writes to [this map](https://github.com/99designs/smartling/blob/master/cli/smartling/status.go#L19)

As with all and any Go...

### CODE REVIEW

**Comment by porty** [comment]
Looks like the methods on `ProjectStatus` work on a copy of the `ProjectStatus` object (the receiver is `statuses ProjectStatus` as opposed to `statuses* ProjectStatus`). This is a hold-over from `ProjectStatus` being a map.

You'll need to change every method now to take a pointer to the `ProjectStatus` type. CI would have failed the build on this, but as you pointed out in Slack there is no CI.

File: cli/smartling/status.go [hunk 1]
```diff
@@ -16,32 +16,38 @@ func MustStatus(remotefile, locale string) smartling.FileStatus {
...
+	statuses.Lock()
+	_, ok := statuses.internal[remotefile]
 	if !ok {
 		mm := make(map[string]smartling.FileStatus)
-		statuses[remotefile] = mm
+		statuses.internal[remotefile] = mm
 	}
-	statuses[remotefile][locale] = fs
+	statuses.internal[remotefile][locale] = fs
+	statuses.Unlock()
```
Comment (porty) [inline cli/smartling/status.go]: Change these to a `defer statuses.Unlock()` call right after the lock call so any extra panics/returns added in this method don't break things

File: cli/smartling/status.go [hunk 2]
```diff
@@ -16,32 +16,38 @@ func MustStatus(remotefile, locale string) smartling.FileStatus {
...
 	c := 0
-	for _, s := range statuses {
+	for _, s := range statuses.internal {
 		for _, status := range s {
 			c += status.AwaitingAuthorizationStringCount()
 			break
 		}
 	}
-
+	statuses.RUnlock()
```
Comment (porty) [inline cli/smartling/status.go]: As above

**Comment by porty** [comment]
It is also worth mentioning that https://godoc.org/golang.org/x/sync/syncmap is a fairly recent alternative to using a mutex and a map - its good to know about but I'm happy to keep with RWMutex

**Comment by navitronic** [comment]
Thanks for review @porty. I've pushed up another commit with changes to address the issues you raised.

I took a look at `sync.Map`, but couldn't find any great examples of it being used in the way we've used maps in this file, will keep it in mind for future though.

**Review by lwc — APPROVED** [review]
nice work.

**Comment by mtibben** [comment]
approve
